### ISSUE TITLE
Company Communicator stop working when use New Teams version

### ISSUE THREAD

**Issue by jkicyjet** [OfficeDev/microsoft-teams-apps-company-communicator#1202]
Could you help advise if we can use the communicator with New Teams? My company turned on to use New version of Teams but I found that the communicator is error as attached, when I get back to normal Teams version "1.6.00.29964 (64-bit)" it worked fine.
please help to advise if we have version that able to use with new Teams please.
https://adoption.microsoft.com/en-us/new-microsoft-teams/

![NewTeams](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150225179/c5993aca-362a-4a53-ab77-ce0d246f468b)

**Comment by gsv022** [comment]
Hi @jkicyjet ,
Thanks for raising the query. We are checking this issue on priority and keep you posted.

**Comment by Fadel1949** [comment]
Yes, it is also a problem. Please help solve this problem. Thank you very much.

**Comment by CRVieiras** [comment]
Ac, mesmo problema aqui

**Comment by Axael85** [comment]
Same issue here. 
<img width="316" alt="CommunicatorErrorNewTeams" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/a70728ca-9f65-48e3-b349-588b20ec0236">

**Comment by StanleyLl0yd** [comment]
Hello, we have the same problem too, please help us solve it.
<img width="522" alt="Capture125" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131160519/8c6093f5-25cb-4195-bea9-72ec18f80fba">

**Comment by 12999StChuck** [comment]
Same issue here too. Once 'New' Teams from 10/2023 is used, it errors out. Uncheck the box for 'New' Teams and revert to previous version it works just fine.

**Comment by gsv022** [comment]
Hi @jkicyjet ,
Thank you for the patience. 

- The app service authentication issue is now resolved, and the changes have been pushed to Company Communicator GitHub repository. 

- If current version of the Company Communicator application is pointing to v5.5, please follow the below procedure to resolve the issue 
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center --> Click on SYNC

- Once the status shows successful within logs section of Deployment Center.
<img width="833" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/9eb1d9a7-02f0-4583-8cd5-6f257eaa9ba8">

 
**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service 
 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6e5045cb-27de-4e4f-9d22-7a7ef300888a)


- Please go to the Overview Section from and restart the app service.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6bb3fe8e-dbf2-4763-98f8-730460dd556d)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

- If current deployed version of the Company Communicator application is pointing to v5.4.1 or previous versions, please upgrade your app to latest version by following the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) as the fix is pushed to the main branch in Company Communicator's GitHub repo.

 
Please let us know if you are still facing the issue.

**Comment by jkicyjet** [comment]
Hi @gsv022 I would like to confirm some before start to sync. base on my screenshot if I need to click on Disconnect external git
to change Repository 
from https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git 
to be https://github.com/OfficeDev/microsoft-teams-company-communicator
before start to sync? 
![DeploymentCenter](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150225179/6b3de652-11db-4e59-83e5-5669b7cd7013)

**Comment by jkicyjet** [comment]
@gsv022 It's worked now. thank you for your help.

**Comment by GeorgiaQian** [comment]
Dear @gsv022 ， my customer has updated Commany communicator to V5.5 and has followed  your sycn steps. But the issue is still here. 
They found the Repo URL and Branch name is differnet with yours.
Their Repo URL is: https://github.com/cristianoag/microsoft-teams-apps-company-communicator.git
Branch: master 

May I know if we need change the Repo url and Branch name?

**Comment by GeorgiaQian** [comment]
@gsv022 , may I know is there any way to confirm the CC version is correctly updated to 5.5?

**Comment by James99IT** [comment]
I followed all the steps here, I have access to the App now in the new Teams but my messages wont send out?
