### ISSUE TITLE
ERROR: unrecognized arguments: --available-to-other-tenants True --oauth2-allow-implicit-flow False

### ISSUE THREAD

**Issue by timoleo23** [OfficeDev/microsoft-teams-apps-company-communicator#893]
Hi,
We have the following issue when running CC deployment script. All parameters have been double checked and the account used to deploy the solution has Azure AD global admin level permission. Any idea of what this problem could be?

```powershell
Azure AD sign-in...
Checking for resources availability...
resource: XXXXCommunicator of type webapp is available.
resource: XXXXCommunicator-data-function of type webapp is available.
resource: XXXXCommunicator-function of type webapp is available.
resource: XXXXCommunicator-prep-function of type webapp is available.
Application Insights resource (XXXXCommunicator) is available.


Creating Azure AD App: XXXXCommunicator-users...
ERROR: unrecognized arguments: --available-to-other-tenants True --oauth2-allow-implicit-flow False


Examples from AI knowledge base:
az ad app create --display-name mytestapp --optional-claims @manifest.json
Create an application with optional claims


az ad app create --display-name mytestapp --identifier-uris https://mytestapp.websites.net/ --app-roles @manifest.json
Create an application with a role


https://docs.microsoft.com/en-US/cli/azure/ad/app#az_ad_app_create
Read more about the command in reference docs
Waiting for app creation to finish...
Azure AD App: XXXXCommunicator-users is created.
Updating app secret...
ERROR: argument --id: expected one argument



Examples from AI knowledge base:
az ad app credential reset --id 00000000-0000-0000-0000-000000000000
append or overwrite an application's password or certificate credentials (autogenerated)


az ad app credential reset --id 00000000-0000-0000-0000-000000000000 --cert "@~/cert.pem"
Append a certificate to the application with the certificate file.



https://docs.microsoft.com/en-US/cli/azure/ad/app/credential#az_ad_app_credential_reset
Read more about the command in reference docs
Azure AD App: XXXXCommunicator-users registered successfully.
Failed to create or update User app in Azure Active Directory. Exiting... 
```

**Comment by v-royavinash** [comment]
@timoleo23  The error is due to Azure CLI version. Please uninstall Azure CLI from your system and re run the script. The script will install the required version of Azure CLI during deployment.

**Comment by gsv022** [comment]
Hi @timoleo23 ,
Could you please let us know the status.

**Comment by timoleo23** [comment]
Hi @gsv022 , yes the problem was fixed with your recommendation to update the Azure CLI. Thank you.

**Comment by spikedfuel** [comment]
I'm also running into the same problem with the azure-cli version 2.53.1 [fully updated]

**Comment by albert-widjaja** [comment]
Yes, same here, even with the latest azure-cli v2.60.0
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/69803760/ddcfa0fd-9d25-44ff-ae4d-3c6a9b9c6994)


I am still having issues with the below error:
`Failed to create or update User app in Azure Active Directory. Exiting...`
